config/routes.rb
Rcms::Application.routes.draw do
  devise_for :users
  resources :settings,:path => ":role/settings/" do
    member do
      get :change_password
      put :update_password
    end
  end
  
  resources :notes
  namespace :client do
    resources :intakes
    resources :dashboards
    resources :individuals do
      member do
        get :medical
        post :medical_information
        get :personal
        post :personal_information
        get :minor
        post :minor_information
      end
    end
    resources :partners,:only => [:new,:create] do
      collection do
        get :partners_family
        post :partners_family_create
      end
    end
    resources :minors do
      member do
        get :medical
        post :medical_information
        get :personal
        post :personal_information
      end
    end
    resources :financials
    resources :career_assessments,:only => [:new,:create]
    resources :reduced_fees,:only => [:new,:create]
    resources :renewal_groups
  end
  
  namespace :counselor do
    resources :dashboards do
      collection do
        get :appointments
        get :case_list
        get :client_list
        get :counselor_status
        get :counselor_down_status
      end
    end
    resources :progress_notes do
      collection do
        post :appointment_progress
      end
    end
    resources :invoices do
      member do
        get :update_values
      end
    end
  end

  namespace :intake_coordinator do
    resources :dashboards do
      member do
        get :intake_details
        get :details
      end
      collection do
        post :assign_case_counselor
        get :calendar
        post :counselor_rooms
      end
    end
    resources :cases do
      collection do 
        get :search_cases
        get :case_list
        post :assign_case
      end
    end
  end
  
  namespace :admin do
    resources :case_prefixes
    resources :users do
      collection do
        get :clients
        get :search_clients
      end
      member do
        put :change_status
      end
    end
    resources :cpt_codes
    resources :misc_payments
    resources :dashboards
    resources :rooms do
      member do
        put :change_status
      end
    end
    resources :forms
    resources :payers do
      collection do
        get :search_payers
      end
    end
  end
  
  namespace :clinical_supervisor do
    resources :dashboards
  end
  
  namespace :clinical_director do
    resources :dashboards
  end
  
  namespace :admin_director do
    resources :dashboards
  end
  
  namespace :accounting_manager do
    resources :dashboards
  end
  
  namespace :reports_manager do
    resources :dashboards
  end
  
  namespace :scheduling_manager do
    resources :dashboards
  end
  
  resources :client_managements,:path => "/:role/client_managements" do
    member do
      post :upload_document
      get :add_client
    end
    collection do
      get :search
      get :search_form
    end
  end
  resources :case_managements,:path => "/:role/case_managements" do
    member do
      post :upload_document
      delete :remove_counselor
    end
    collection do
      post :add_counselor
      post :counselor_permisson
    end
  end
  resources :reminders,:path => "/:role/reminders"
  resources :documents,:path => "/:role/documents" do
    collection do
      get :case_documents
      post :upload_client_document
    end
  end
  
  resources :adolesment_intakes,:path => "/:role/adolesment_intakes" do
    member do
      get :client_adolesment_intake
      post :client_adolesment
    end
  end
  resources :discharge_summary,:path => "/:role/discharge_summary" do
    member do
      get :client_discharge_summary
      post :client_discharge
    end
  end
  resources :initial_evalutions,:path => "/:role/initial_evalutions" do
    member do
      get :client_intake_evalution
      post :client_intake
    end
  end
  resources :accountings,:path => "/:role/accountings" do
    collection do
      post :m_payment
      post :payer_account
      post :session_fee
    end
    member do
      get :update_session_payment
    end
  end
  
  resources :appointments,:path => "/:role/:shedule_id/appointments"
  resources :schedulings,:path => "/:role/schedulings"
  
  match "/:role/initial_evalutions/:case_id/new" => "initial_evalutions#new",:as => "initial_evalution_new"
  match "/:role/discharge_summary/:case_id/new" => "discharge_summary#new",:as => "discharge_summary_new"
  match "/:role/adolesment_intakes/:case_id/new" => "adolesment_intakes#new",:as => "adolesments_intake_new"
  match "/:role/intakes/:id" => "client/intakes#show",:as => "intake_form_details"
  match "/:role/reduced_fees/:id" => "client/reduced_fees#show",:as => "reduced_fee_details"

  root :to => 'home#index'

end

app/models/intake_coordinator.rb
class IntakeCoordinator < User
  # attr_accessible :title, :body
end

app/controllers/intake_coordinator/cases_controller.rb
class IntakeCoordinator::CasesController < ApplicationController
  before_filter :is_login
  before_filter :is_correct_user,:except => :update
  
  def index
    if params[:query] and params[:query] != "all"
      @cases = Case.where("status = '#{params[:query]}'")
    else
      @cases = Case.all
    end
  end
  
  def new
    @intake_forms = IntakeForm.where("case_id IS NULL")
    @cases = Case.all
    @case = Case.new
  end
  
  #creating case number
  def create
    @intake_forms = IntakeForm.where("case_id IS NULL")
    @cases = Case.all
    @intake_form = IntakeForm.find params[:case][:intake_form_id]
    respond_to do |format|
      @case = Case.new(params[:case])
      @case.status = 'inactive'
      @intake_ids = params[:other_intakes]
      if @case.save
        CaseClient.create(:case_id => @case.id,:client_id => @intake_form.user_id)
        CaseIntakeForm.create(:case_id =>@case.id,:intake_form_id => @case.intake_form_id)
        @intake_form.update_attribute(:case_id,@case.id)
        update_doc(@intake_form.id,@case.id)
        if params[:other_intakes]
          params[:other_intakes].split(",").each do |int|
            unless int.nil?
              intake = IntakeForm.find(int)
              intake.update_attribute(:case_id,@case.id)
              CaseClient.create(:case_id => @case.id,:client_id => intake.user_id) if !CaseClient.exists?(:case_id => @case.id,:client_id => intake.user_id)
              update_doc(int,@case.id)
            end
          end
        end
      end
      format.js
    end
  end
  
  def search_cases
    @intake_ids = params[:intake_id]
    @cases = Case.where("number ILIKE '%#{params[:search]}%'")
  end
  
  def assign_case
    respond_to do |format|
      if params[:case_id] and !params[:intake_ids].blank?
        params[:intake_ids].split(",").each do |int|
          unless int.nil?
            intake = IntakeForm.find(int)
            intake.update_attribute(:case_id,params[:case_id])
            CaseClient.create(:case_id => params[:case_id],:client_id => intake.user_id) if !CaseClient.exists?(:case_id => params[:case_id],:client_id => intake.user_id)
            update_doc(int,params[:case_id])
          end
        end
        @redirect = true
      else
        @redirect = false
        if params[:case_id]
          @alert = "First you need to select intake from above box!"
        else
          @alert = "Assign a case before proceeding!"
        end
      end
      format.js
    end
  end
  
  def update
    @case = Case.find(params[:id])
    @case.update_attribute(:status, params[:status])
    respond_to do |format|
      format.js { head :no_content }
    end
  end
  
  def show
    @case = Case.find(params[:id])
    @documents = @case.documents
    @document = Document.new
    @client_document = ClientDocument.new
  end
  
  def update_doc(int,cs)
    doc = Document.find_by_intake_form_id(int)
    if doc
      doc.update_attribute(:case_id,cs)
    end
  end
end

app/controllers/intake_coordinator/dashboards_controller.rb
class IntakeCoordinator::DashboardsController < ApplicationController
  before_filter :is_login
  before_filter :is_correct_user,:except => [:calendar]
  def index
    @cases = Case.where("counselor_id IS NULL")
  end
  
  def intake_details
    @case = Case.find params[:id]
    @intake_form = IntakeForm.all_information(@case.intake_form_id).first
    if !@intake_form.medical_id.nil?
      @medical_reasons = MedicalReason.where("medical_id = '#{@intake_form.medical_id}'")
      @medications = Medication.where("medical_id = '#{@intake_form.medical_id}'")
    else
      @medical_reasons = []
      @medications = []
    end
    render
  end
  
  def details
    @intake_form = IntakeForm.all_information(params[:id]).first
    if !@intake_form.medical_id.nil?
      @medical_reasons = MedicalReason.where("medical_id = '#{@intake_form.medical_id}'")
      @medications = Medication.where("medical_id = '#{@intake_form.medical_id}'")
    else
      @medical_reasons = []
      @medications = []
    end
    @client = User.find(@intake_form.user_id)
    @partners = @client.partners.where("intake_type = ?", @intake_form.intake_type)
    @intakes = []
    @partners.each do |int|
      @user = User.find_by_email(int.email)
      if @user
        @user.intake_forms.each do |i_form|
          @intakes<<[int.name,int.date_of_birth,@user.id,i_form.id]
        end
      end
    end
    render
  end
  
  def assign_case_counselor
    @case = Case.find(params[:case_in])
    @counselor = Counselor.find(params[:con]).id
    @intake_form = IntakeForm.find(params[:intake_form_id])
    @client = @intake_form.user
    @appointment = Appointment.create(:counselor_id => @counselor,:intake_form_id => @intake_form.id,:client_id => @client.id,:case_id => @case.id, :status => params[:status])
    @case.update_attribute(:counselor_id,@counselor)
    CaseCounselor.create(:case_id => @case.id,:counselor_id => @counselor)
    render
  end
  
  def calendar
    @date = params[:date].present? ? Date.parse(params[:date]) : Date.today
    @start_date = @date.beginning_of_week(:sunday).to_date
    @end_date = @date.end_of_week(:sunday).to_date
    @rooms = Room.all
    @counselors = Counselor.all
    @cases = Case.all
    @counselor_room = CounselorAvailability.new
    @counselor_availabilities = CounselorAvailability.where("start_at BETWEEN '#{@start_date} 00:01:01' and '#{@end_date} 23:59:59'")
    @common_appointments = Array.new
    @main_appoints = Array.new
    @counselor_availabilities.each do |a|
      @common_appointments << a.start_at.strftime("%Y-%m-%d %H:%M:%S")+a.room_id.to_s
      @main_appoints << a
    end
    respond_to do |format|
      format.html
      format.js
    end
  end
  
end

app/helpers/intake_coordinator/cases_helper.rb
module IntakeCoordinator::CasesHelper
end

app/helpers/intake_coordinator/dashboards_helper.rb
module IntakeCoordinator::DashboardsHelper
end

app/views/intake_coordinator/cases/_case_creation_form.html.erb
<div class="clearFix"></div>
<%= form_for @case, :url => intake_coordinator_cases_path(@case), :remote => true do |f| %>
  <%= f.hidden_field :intake_form_id %>
  <%= hidden_field_tag "other_intakes" %>
  <div class="box mt15 pRelative">
    <ul class="list-upload list-upload-mb">
      <li>
        <div class="greenBox">Create<br />New Case</div>
        <div class="darkBoxGray">
          <h6 class="selectHeading"><span>1</span> Case Number</h6>
          <%= f.select :prefix,options_for_select(CasePrefix.all.collect{|prefix| [prefix.prefix]},:selected => f.object.prefix),{},:style => 'padding: 7px;' %>
          <%= f.text_field :extension,:style => "width:135px;" %>
          <div style="width:300px;">
            <%= validation_error(@case.errors["extension"]) %>
          </div>
        </div>
        <div class="darkBoxGray lightBoxGray">
          <h6 class="selectHeading"><span>2</span> CASE NAME</h6>
          <%= f.text_field :case_name,:class=>"input-selectFile", :id=>"case-name" %>
          <div style="width:200px;">
            <%= validation_error(@case.errors["case_name"]) %>
          </div>
          <div class="btn-createnew" >
            <button class="btn-submit" title="CONTINUE" style="border:none;background: none;">Save</button><em></em>
          </div>	
        </div>
        <div class="clearFix"></div>
      </li>
    </ul>
  <% end %>

</div>
<script>
  $(".btn-submit").click(function() {
    var st = false;
    var intake_id;
    $("input.unique").each(function() {
      if ($(this).is(":checked")) {
        st = true;
        intake_id = $(this).val();
      }
    });
    if (st == true) {
      $("#case_intake_form_id").val(intake_id);
      return true;
    } else {
      alert("Select intake form in the above box");
      return false;
    }
  });
</script>

app/views/intake_coordinator/cases/_existing_cases.html.erb
<table class="table-borLess" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tr>
    <td colspan="3" bgcolor="#363636"><h6 class="clientList">APPLY TO EXISTING CASE</h6></td>
    <td bgcolor="#363636" colspan="2">
      <div style="color:red;" >
        <%= form_tag(search_cases_intake_coordinator_cases_path, :remote => true, :method => "get") do   %>
          <%= hidden_field_tag "intake_id" %>
          <%= text_field_tag :search,"", :class=>"input-selectFile", :id=>"case-for-search", :style=>"margin-left: 30px;" %>
          <%= submit_tag "Search", :title=>"Search", :class=>"btn-createnew2", :style=>"color: white;background-color: #a8cf75;" %>
        <% end %>
      </div>
    </td>
  </tr>
  <% cases.each do |cas| %>
    <tr>
      <%= form_tag assign_case_intake_coordinator_cases_path,:remote => true do %>
        <%= hidden_field_tag "intake_ids" %>
        <td><%= check_box_tag "case_id","#{cas.id}" %></td>
        <td><%= link_to cas.number, case_management_path(current_user.role,cas) %></td>
        <td><%= cas.case_name %></td>
        <td><%= cas.created_at.strftime("%b %d, %Y") %></td>
        <td><%= submit_tag "assign" %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<script>
  $(document).ready(function() {
    $("input#case_check").each(function() {
      if ($(this).is(":checked")) {
        $(this).trigger('click');
      }
    });
    $("#intake_ids").val('');
    $("#intake_id").val('');
    $("#other_intakes").val('');
  });
</script>

app/views/intake_coordinator/cases/_form.html.erb
<div class="calendarColumn">
  <div class="box">
    <table class="table-borLess table-copleted" cellpadding="0" cellspacing="0" width="100%" border="0">
      <tr>
        <td colspan="5"><h6 class="compHeading">LIST OF COMPLETED INTAKES</h6></td>
      </tr>
      <tr class="whitecolor">
        <td></td>
        <td>NAME</td>
        <td>DOB</td>
        <td>COMPLETED</td>
        <td>TYPE</td>
      </tr>
      <% @intake_forms.each do |i| %>
        <tr>
          <% @client = User.find(i.user_id) %>
          <% partners = @client.partners.where("intake_type = ?", i.intake_type) %>
          <td style="padding: 5px 0;"><input type="checkbox" class="unique" value="<%= i.id %>" onclick="display_intake_details(this, '<%= i.id %>')"></td>
          <td  style="padding: 5px 0;"><strong><%= @client.full_name %></strong></td>
          <td  style="padding: 5px 0;"><%= @client.date_of_birth %></td>
          <td  style="padding: 5px 0;">5/9/13</td>
          <td  style="padding: 5px 0;"><%= i.intake_type %></td>
        </tr>
        <% if partners.present? %>
          <% partners.each do |partner| %>
            <tr>
              <td style="border-top:none; padding: 1px 0;"> </td>
              <td style="border-top:none; padding: 1px 0;"><strong><%= partner.name %></strong></td>
              <td style="border-top:none; padding: 1px 0;"><%= partner.date_of_birth %></td>
              <td style="border-top:none; padding: 1px 0;">5/9/13</td>
              <td style="border-top:none; padding: 1px 0;"></td>
            </tr>
          <% end %>
        <% end %>
      <% end %>
    </table>
  </div>
</div>
<div class="calendarColumn" id="intake_from_information">
</div>
<div id="create-case">
  <%= render :partial => "case_creation_form" %>
</div>
<div class="box mt15" id="existing-cases-list">
  <%= render :partial => "existing_cases",:locals => {:cases => @cases} %>
</div>
<div class="clearFix"></div>
<script>
  $(document).ready(function() {
    $("input.unique").each(function() {
      if ($(this).is(":checked")) {
        $("#intake_ids").val($(this).val() + ',');
        $("#intake_id").val($(this).val() + ',');
        $("#other_intakes").val($(this).val() + ',');
        $.ajax({
          url: "/intake_coordinator/dashboards/" + $(this).val() + "/details"
        });
      }
    });
  });
</script>

app/views/intake_coordinator/cases/_intake_form_details.html.erb
<div class="box pRelative">
  <%= form_tag(assign_case_counselor_intake_coordinator_dashboards_path(:case_in => @case.id), :remote => true) do  %>
    <%= hidden_field_tag "con" %>
  <%= hidden_field_tag "intake_form_id",@intake_form.id %>
    <div class="commonr row-intake">
      <div class="columnIntake"><%= @intake_form.intake_type.split("_").join(" ") %> INTAKE</div>
      <div class="columnOffice">
        FOR OFFICE USE
        <ul class="list-normal">
          <li><%= radio_button_tag "status","urgent" %><a style="padding:0px" title="waistlist" href="#">urgent</a></li>
          <li><%= radio_button_tag "status","confirm" %><a style="padding:0px" title="waistlist" href="#">confirm</a></li>
          <li><%= radio_button_tag "status","waitlist" %><a style="padding:0px" title="waistlist" href="#">wait list</a></li>
        </ul>
      </div>
      <div class="columnDate">
        <div class="btn-createnew">
          <%= submit_tag "save" , :onclick => "return validateform()" %><em></em>
        </div>
        <p><%= Date.today.strftime("%b %d %Y") %><br><span>start date</span></p>
      </div>
    </div>
    <br/>
  <% end %>
  <div class="commonrow">
    <div class="columnPersonal"><a title="PERSONAL" href="#">PERSONAL</a></div>
    <div class="columnMedical"><a title="COUNSELING INFO" href="#">COUNSELING INFO</a>    |    <a title="MEDICAL" href="#">MEDICAL</a></div>
    <div class="columnViewall"><a title="view all" href="#">view all</a></div>
  </div>
  <ul id="collexp-menu_1" class="collexpMenu list-intale">
    <li>
      <div title="PERSONAL INFORMATION" class="expanded" onclick="display_child_li(this);">1. PERSONAL INFORMATION</div>
      <ul>
        <li>
          <ul class="list-contactinfo">
            <li>
              <ul class="list-normal list-religious">
                <li><span>NAME:</span><br> <%= @intake_form.name %></li>
                <li><span>SEX:</span><br><%= @intake_form.gender %></li>
                <li><span>DATE OF BIRTH:</span><br><%= @intake_form.date_of_birth %></li>
                <li><span>AGE:</span><br><%= Date.today.year - @intake_form.date_of_birth.to_date.strftime("%Y").to_i %></li>
              </ul>
            </li>
            <li>
              <ul class="list-normal list-religious">
                <li><span>MARITAL STATUS:</span><br><%= @intake_form.marital_status %></li>
                <li><span>DATE OF MARRIAGE:</span><br> <%= @intake_form.date_of_marriage %></li>
                <li><span>DATE OF SEPARATION:</span><br> <%= @intake_form.date_of_seperation %></li>
                <li><span>NUMBER OF MARRIAGES:</span><br> <%= @intake_form.no_of_marriages %></li>
                <li><span>BELIEVE IN GOD</span><br><%= @intake_form.believe_in_god %></li>
                <li><span>RELIGIOUS PREFERENCE</span><br><%= @intake_form.religious_preference %></li>
                <li><span>CHURCH CURRENTLY ATTENDING</span><br><%= @intake_form.current_church %></li>
                <li><span>MEMBER OF RPC</span><br><%= @intake_form.member_of_redeemer_church %></li>
                <li><span>INFLUENCE RELIGION ON DAILY LIFE</span><br><%= @intake_form.day_to_day_activity %></li>
              </ul>
            </li>
            <li>
              <ul class="list-normal list-religious">
                <li><span>OCCUPATION:</span><br> <%= @intake_form.occupation %></li>
                <li><span>EMPLOYER:</span><br> <%= @intake_form.employer %></li>
                <li><span>YEARS  WITH CURRENT EMPLOYER:</span><br><%= @intake_form.time_with_current_emp %></li>
                <li><span>ANNUAL INCOME:</span><br> <%= @intake_form.annual_income %></li>
                <li><span>SCHOOL:</span><br> <%= @intake_form.school %></li>
                <li><span>FIELD OF STUDY:</span><br> <%= @intake_form.field_of_study %></li>
                <li><span>DEGREE:</span><br> <%= @intake_form.degree %></li>
                <li><span>STATUS:</span><br> <%= @intake_form.status %></li>
              </ul>
            </li>
          </ul>
        </li>								
      </ul>
    </li>
    <li>
      <div title="CONTACT INFORMATION" class="expanded" onclick="display_child_li(this);">2. COUNSELING | MEDICAL INFORMATION</div>
      <ul>
        <li>
          <ul class="list-contactinfo">
            <li>
              <ul class="list-normal list-religious">
                <li><span>REASON FOR COMING IN:</span><br> <%= @intake_form.name %></li>
                <li><span>AREA OF BIGGEST IMPACT:</span><br> <%= @intake_form.address %>, <%= @intake_form.city %>, <%= @intake_form.state %>&nbsp;&nbsp;<%= @intake_form.zip %></li>
                <li><span>WHEN DID IT START:</span><br> <%= @intake_form.gender %></li>
                <li><span>DO OTHERS SEE IT:</span><br> <%= @intake_form.date_of_birth %></li>
                <li><span>SEVERITY:</span><br> <%= @intake_form.date_of_birth %></li>
                <li><span>CURRENT PROBLEMS:</span><br> <% problems = @intake_form.current_problems.nil? ? nil : @intake_form.current_problems.split("-")-[""]-["\n"] %><% if problems and !problems.empty? %><% problems.each_with_index do |p,index| %> <%= index+1 %>.<%= p %><br /> <% end %> <% end %></li>
              </ul>
            </li>
            <li>
              <ul class="list-normal list-religious">
                <li><span>PSYCHIATRIC HOSPITALIZATIONS:</span><br> <%= @intake_form.hospitalized %></li>
                <li><span>EXPLAIN:</span><br> <%= @intake_form.h_explain %></li>
                <li><span>DATE:</span><br><%= @intake_form.living_with %></li>
                <li><span>PRIOR COUNSELING:</span><br> <%= @intake_form.counseling_before %></li>
                <li><span>PREVIOUS EXPERIENCE:</span><br> <%= @intake_form.p_explain %></li>
                <li><span>FUTURE GAINS:</span><br> <%= @intake_form.gain_from_counseling %></li>
              </ul>
            </li>
            <li>
              <ul class="list-normal list-religious">
                <li><span>RATE PHYSICAL HEALTH:</span><br> <%= @intake_form.rate %></li>
                <li><span>DATE OF LAST PHYSICAL:</span><br> <%= @intake_form.date_of_last_p_exam %></li>
                <li><span>CURRENT PHYSICAL PROBLEMS:</span><br><%= @intake_form.e_physical_problems %></li>
                <li><span>EXPLAIN:</span><br> <%= @intake_form.c_explain %></li>
                <% @medical_reasons.each do |med| %>
                  <li><span>PRIOR HOSPITALIZATIONS:</span><br> <%= med.previous_hospital %></li>
                  <li><span>DATE:</span><br> <%= med.previous_hospital_date %></li>
                <% end %>
                <% @medications.each do |medi| %>
                  <li><span>CURRENT MEDICATIONS:</span><br> <%= medi.medician %></li>
                  <li><span>DOSAGE:</span><br> <%= medi.dosage %></li>
                <% end %>
              </ul>
            </li>
          </ul>
        </li>								
      </ul>
    </li>
    <li>
      <div title="EMERGENCY CONTACT" class="expanded" onclick="display_child_li(this);">3.   EMERGENCY CONTACT</div>
      <ul>
        <li>
          <div class="table-emergencyContact">
            <div class="row">
              <div class="column">NAME:</div>
              <div class="column">RELATIONSHIP:</div>
              <div class="column">PHONE:</div>
              <div class="column">EMAIL:</div>
            </div>	
            <div class="row">
              <div class="column"><%= @intake_form.contact_name %></div>
              <div class="column"><%= @intake_form.relationship %></div>
              <div class="column"><%= number_to_phone(@intake_form.contact_no) %></div>
              <div class="column"><%= @intake_form.contact_email %></div>
            </div>	
          </div>									
        </li>
      </ul>
    </li>
  </ul>
  <div class="clearFix"></div>
</div>	
<script>
  $(document).ready(function() {
    setTimeout(function() {
      $('#collexp-menu_1 > li > div.expanded + ul').slideToggle('medium');
    }, 250);
  });

  function display_child_li(th) {
    $(th).toggleClass('expanded').toggleClass('collapsed').not(th).parent().find('> ul').slideToggle('medium');
    $(th).toggleClass('expanded').toggleClass('collapsed').parent().find('> ul').slideToggle('medium');
  }

  function assign_case_counselor(ids) {
    $.ajax({
      url: "/intake_coordinator/dashboards/assign_case_counselor",
      data: {
        ids: ids
      },
      method: 'POST'
    });
  }

  function validateform() {
    var coun_id = $("#con").val();
    if (coun_id === "") {
      alert("select counselor from left pane!");
      return false;
    }
  }

  $(document).ready(function() {
    $('#start_at, #end_at').datetimepicker({
      timepicker: true,
      format: 'Y-m-d H:i'
    });
  });
</script>

app/views/intake_coordinator/cases/assign_case.js.erb
<% if @redirect == true %>
  window.location.href = '/';
<% else %>
  alert('<%= @alert %>');
<% end %>

app/views/intake_coordinator/cases/create.js.erb
<% if params[:cas_id].blank? %>
  <% if @case.errors.any? %>
    $("#create-case").html("<%= escape_javascript render :partial => "intake_coordinator/cases/case_creation_form" %>");
    $("#other_intakes").val('<%= @intake_ids %>')
  <% else %>
    window.location.href = '<%= root_path %>'
  <% end %>
<% else %>
  window.location.href = '<%= root_path %>'
<% end %>

app/views/intake_coordinator/cases/index.html.erb
<div><%= link_to "View all", intake_coordinator_cases_path(:query => "all"),:class => params[:query] == "all" ? "selected" : "" %> | <%= link_to "Active", intake_coordinator_cases_path(:query => "active"),:class => params[:query] == "active" ? "selected" : "" %> | <%= link_to "Inactive", intake_coordinator_cases_path(:query => "inactive"),:class => params[:query] == "inactive" ? "selected" : "" %> | <%= link_to "Discharged", intake_coordinator_cases_path(:query => "discharged"),:class => params[:query] == "discharged" ? "selected" : "" %></div>
<div id="tabs" class="commonr">
  <div class="box">
    <table class="table-accounting table-case-final" cellpadding="0" cellspacing="0" width="100%" border="0">
      <tr>
        <td>CASE NAME</td>
        <td>CASE NUMBER</td>
        <td>CLIENT</td>
        <td>DOB</td>
        <td>STATUS</td>
      </tr>
      <% @cases.each do |cs| %>
        <tr>
          <td><span><%= link_to cs.case_name, case_management_path(current_user.role,cs) %></span></td>
          <td><%= link_to cs.number, case_management_path(current_user.role,cs) %></td>
          <td>
            <% cs.case_clients.each do |intake| %>
              <div><%= link_to intake.client.full_name, client_management_path(current_user.role,intake.client) %></div>
            <% end %>
          </td>
          <td>
            <% cs.case_clients.each do |intake| %>
              <div><%= intake.client.date_of_birth.strftime("%m/%d/%Y") %></div>
            <% end %>
          </td>
          <td><span><%= cs.status %></span></td>
        </tr>
      <% end %>
    </table>
    <div class="clearFix"></div>
  </div>
</div>
<div class="clearFix"></div>
<style>
  a.selected{
    text-decoration: none;
  }
</style>

app/views/intake_coordinator/cases/new.html.erb
<div id="new_case_form">
  <%= render :partial => "intake_coordinator/cases/form" %>
</div>

app/views/intake_coordinator/cases/search_cases.js.erb
$("#existing-cases-list").html("<%= escape_javascript render :partial => "existing_cases",:locals => {:cases => @cases} %>");
$("#intake_ids,#intake_id").val(<%= @intake_ids %>);