config/routes.rb
Rcms::Application.routes.draw do
  devise_for :users
  resources :settings,:path => ":role/settings/" do
    member do
      get :change_password
      put :update_password
    end
  end
  
  resources :notes
  namespace :client do
    resources :intakes
    resources :dashboards
    resources :individuals do
      member do
        get :medical
        post :medical_information
        get :personal
        post :personal_information
        get :minor
        post :minor_information
      end
    end
    resources :partners,:only => [:new,:create] do
      collection do
        get :partners_family
        post :partners_family_create
      end
    end
    resources :minors do
      member do
        get :medical
        post :medical_information
        get :personal
        post :personal_information
      end
    end
    resources :financials
    resources :career_assessments,:only => [:new,:create]
    resources :reduced_fees,:only => [:new,:create]
    resources :renewal_groups
  end
  
  namespace :counselor do
    resources :dashboards do
      collection do
        get :appointments
        get :case_list
        get :client_list
        get :counselor_status
        get :counselor_down_status
      end
    end
    resources :progress_notes do
      collection do
        post :appointment_progress
      end
    end
    resources :invoices do
      member do
        get :update_values
      end
    end
  end

  namespace :intake_coordinator do
    resources :dashboards do
      member do
        get :intake_details
        get :details
      end
      collection do
        post :assign_case_counselor
        get :calendar
        post :counselor_rooms
      end
    end
    resources :cases do
      collection do 
        get :search_cases
        get :case_list
        post :assign_case
      end
    end
  end
  
  namespace :admin do
    resources :case_prefixes
    resources :users do
      collection do
        get :clients
        get :search_clients
      end
      member do
        put :change_status
      end
    end
    resources :cpt_codes
    resources :misc_payments
    resources :dashboards
    resources :rooms do
      member do
        put :change_status
      end
    end
    resources :forms
    resources :payers do
      collection do
        get :search_payers
      end
    end
  end
  
  namespace :clinical_supervisor do
    resources :dashboards
  end
  
  namespace :clinical_director do
    resources :dashboards
  end
  
  namespace :admin_director do
    resources :dashboards
  end
  
  namespace :accounting_manager do
    resources :dashboards
  end
  
  namespace :reports_manager do
    resources :dashboards
  end
  
  namespace :scheduling_manager do
    resources :dashboards
  end
  
  resources :client_managements,:path => "/:role/client_managements" do
    member do
      post :upload_document
      get :add_client
    end
    collection do
      get :search
      get :search_form
    end
  end
  resources :case_managements,:path => "/:role/case_managements" do
    member do
      post :upload_document
      delete :remove_counselor
    end
    collection do
      post :add_counselor
      post :counselor_permisson
    end
  end
  resources :reminders,:path => "/:role/reminders"
  resources :documents,:path => "/:role/documents" do
    collection do
      get :case_documents
      post :upload_client_document
    end
  end
  
  resources :adolesment_intakes,:path => "/:role/adolesment_intakes" do
    member do
      get :client_adolesment_intake
      post :client_adolesment
    end
  end
  resources :discharge_summary,:path => "/:role/discharge_summary" do
    member do
      get :client_discharge_summary
      post :client_discharge
    end
  end
  resources :initial_evalutions,:path => "/:role/initial_evalutions" do
    member do
      get :client_intake_evalution
      post :client_intake
    end
  end
  resources :accountings,:path => "/:role/accountings" do
    collection do
      post :m_payment
      post :payer_account
      post :session_fee
    end
    member do
      get :update_session_payment
    end
  end
  
  resources :appointments,:path => "/:role/:shedule_id/appointments"
  resources :schedulings,:path => "/:role/schedulings"
  
  match "/:role/initial_evalutions/:case_id/new" => "initial_evalutions#new",:as => "initial_evalution_new"
  match "/:role/discharge_summary/:case_id/new" => "discharge_summary#new",:as => "discharge_summary_new"
  match "/:role/adolesment_intakes/:case_id/new" => "adolesment_intakes#new",:as => "adolesments_intake_new"
  match "/:role/intakes/:id" => "client/intakes#show",:as => "intake_form_details"
  match "/:role/reduced_fees/:id" => "client/reduced_fees#show",:as => "reduced_fee_details"

  root :to => 'home#index'

end

app/controllers/initial_evalutions_controller.rb
class InitialEvalutionsController < ApplicationController
  
  def new
    @case = Case.find(params[:case_id])
    @client = @case.intake_form.user
    @intake_evalution = IntakeEvalution.new
  end
  
  def create
    @case = Case.find(params[:intake_evalution][:case_id])
    @client = @case.intake_form.user
    @intake_evalution = IntakeEvalution.new(params[:intake_evalution])
    if @intake_evalution.save
      @document = Document.new(:user_id => current_user.id,:case_id =>@case.id,:client_id =>@client.id,:intake_evalution_id => @intake_evalution.id,:doc_type => "intake_evalution")
      @document.save(:validate => false)
      redirect_to edit_initial_evalution_path(current_user.role,@intake_evalution)
    else
      render :action => :new
    end
  end
  
  def client_intake_evalution
    @client = Client.find(params[:id])
    @intake_evalution = IntakeEvalution.new
  end
  
  def client_intake
    @client = Client.find(params[:intake_evalution][:client_id])
    @intake_evalution = IntakeEvalution.new(params[:intake_evalution])
    if @intake_evalution.save
      @document = Document.new(:user_id => current_user.id,:client_id =>@client.id,:intake_evalution_id => @intake_evalution.id,:doc_type => "intake_evalution")
      @document.save(:validate => false)
      redirect_to edit_initial_evalution_path(current_user.role,@intake_evalution)
    else
      render :action => :client_intake_evalution
    end
  end
  
  def edit
    @intake_evalution = IntakeEvalution.find(params[:id])
  end
  
  def update
    @intake_evalution = IntakeEvalution.find(params[:id])
    if @intake_evalution.update_attributes(params[:intake_evalution])
      redirect_to edit_initial_evalution_path(current_user.role,@intake_evalution)
    else
      render :action => :edit
    end
  end
end

app/helpers/initial_evalutions_helper.rb
module InitialEvalutionsHelper
end

app/views/initial_evalutions/_form.html.erb
<%= f.error_messages %>  
<div class="bor">
</div>
<h2>HISTORY</h2>
<ul class="list-dischargeBox">
  <li>
    <div class="lightGrayColor">
      <div class="resonHeading">
        <h6 class="grayBoxHeading">PSYCHOSOCIAL HISTORY:</h6>
        <p><span>(Relevant Family, Social &amp; Employment History. For Children and Adolescents. include developmental history. e.g. prenatal, academic &amp; social history)</span></p>
      </div>
      <%= f.text_area :psychosocial_history,:class => "textarea-reson" %>
    </div>
  </li>
  <li>
    <div class="midGrayColor">
      <div class="resonHeading">
        <h6 class="grayBoxHeading">PAST PSYCHIATRIC AND TREATMENT HISTORY</h6>
        <p><span>(Describe previous psychiatric illnesses. including any mental health and/or sub-stance abuse treatment)</span></p>
      </div>
      <%= f.text_area :past_psychiatric_and_treatment,:class => "textarea-reson" %>
    </div>
  </li>
  <li>
    <div class="darkGrayColor">
      <div class="resonHeading">
        <h6 class="grayBoxHeading">MEDICAL HISTORY</h6>
        <p><span>(Significant past and present medical treatments and conditions)</span></p>
      </div>
      <%= f.text_area :medical_history,:class => "textarea-reson" %>
    </div>
  </li>
</ul>
<div class="gaf">
  <h2>RISK ASSESSMENT</h2>
  <ul class="list-dischargeBox">
    <li>
      <div class="lightGrayColor" id="psychosocial_history">
        <h6 class="grayBoxHeading">PSYCHOSOCIAL HISTORY:</h6>
        <p><%= f.check_box :risk_physical_history,{},"none",false %> None </p>
        <p><%= f.check_box :risk_physical_history,{},"ideation",false %> Ideation </p>
        <p><%= f.check_box :risk_physical_history,{},"plan",false %> Plan </p>
        <p><%= f.check_box :risk_physical_history,{},"intent",false %> Intent </p>
        <p><%= f.check_box :risk_physical_history,{},"patient_agreed_to_safety_plan",false %> Patient Agreed to Safety Plan </p>
        <p><%= f.check_box :risk_physical_history,{},"denial",false %> Denial </p>
      </div>
    </li>
    <li>
      <div class="midGrayColor" id="homicidality">
        <h6 class="grayBoxHeading">HOMICIDALITY:</h6>
        <p><%= f.check_box :homicidality,{},"none",false %> None </p>
        <p><%= f.check_box :homicidality,{},"ideation",false %> Ideation </p>
        <p><%= f.check_box :homicidality,{},"plan",false %> Plan </p>
        <p><%= f.check_box :homicidality,{},"intent",false %> Intent </p>
        <p><%= f.check_box :homicidality,{},"patient_agreed_to_safety_plan",false %> Patient Agreed to Safety Plan </p>
        <p><%= f.check_box :homicidality,{},"denial",false %> Denial </p>
      </div>
    </li>
    <li>
      <div class="darkGrayColor" id="violent">
        <h6 class="grayBoxHeading">VIOLENT:</h6>
        <p><%= f.check_box :violent,{},"none",false %> None </p>
        <p><%= f.check_box :violent,{},"ideation",false %> Ideation </p>
        <p><%= f.check_box :violent,{},"plan",false %> Plan </p>
        <p><%= f.check_box :violent,{},"intent",false %> Intent </p>
        <p><%= f.check_box :violent,{},"patient_agreed_to_safety_plan",false %> Patient Agreed to Safety Plan </p>
        <p><%= f.check_box :violent,{},"denial",false %> Denial </p>
      </div>
    </li>


    <li>
      <div class="lightGrayColor lightGrayColorh" id="able_to_care">
        <h6 class="grayBoxHeading">ABLE TO CARE FOR SELF:</h6>
        <p>
          <%= f.check_box :able_to_care_self,{},"yes",false %> YES
          <%= f.check_box :able_to_care_self,{},"no",false %> NO
        </p>
        <p>IF NOT PLEASE EXPLAIN:</p>
        <%= f.text_area :if_not_explain,:class => "textarea-reson textarea-able" %>
      </div>
    </li>
    <li>
      <div class="midGrayColor">
        <h6 class="grayBoxHeading">RISKS OF HARM TO SELF OR OTHERS:</h6>
        <p><%= f.text_area :risks_of_harm_to_self,:class => "textarea-reson textarea-able" %></p>
        <p>SAFETY PLAN FOR HIGH RISK BEHAVIOR</p>
        <%= f.text_area :safty_plan_for_high_risk,:class => "textarea-reson textarea-able" %>
      </div>
    </li>
    <li>
      <div class="darkGrayColor">
        <h6 class="grayBoxHeading">TREATMENT PLAN:</h6>
        <p><%= f.check_box :individual_psycho_2 %> Individual psycho therapy sessions 2 &times; WEEK</p>
        <p><%= f.check_box :individual_psycho_1 %> Individual psycho therapy sessions 1 &times; PER WEEK</p>
        <p><%= f.check_box :plan %> Plan</p>
        <p><%= f.check_box :intent %> Intent</p>
        <p><%= f.check_box :patient_agreed_to_safty_plan %> Patient Agreed to Safety Plan</p>
        <p><%= f.check_box :dental %> Denial</p>
      </div>
    </li>
  </ul>
  <div class="pleft15">
    <p>Indicate to whom referral is made, if known:</p>
    <%= f.text_area :whom_referal_made,:rows => 2,:cols => 20,:class => "textarea-comment" %>
  </div>
</div>
<div class="gaf">
  <h2>CLINICAL SUMMARY/FORMULATION:
    <div class="intakeGaf midGrayColor">Intak GAF<%= f.text_field :intake_gaf,:class => "input-gaf" %></div>
  </h2>
</div>
<div class="clearFix"></div><br/>
<div class="btn-createnew"><input type="submit" title="Submit" name="" value="Submit" /><em></em></div>
<div class="clearFix"></div>
<script>
  $("#psychosocial_history p input[type='checkbox']").click(function() {
    $("#psychosocial_history p input[type='checkbox']").not(this).attr("checked", false);
  });

  $("#homicidality p input[type='checkbox']").click(function() {
    $("#homicidality p input[type='checkbox']").not(this).attr("checked", false);
  });

  $("#violent p input[type='checkbox']").click(function() {
    $("#violent p input[type='checkbox']").not(this).attr("checked", false);
  });

  $("#able_to_care p input[type='checkbox']").click(function() {
    $("#able_to_care p input[type='checkbox']").not(this).attr("checked", false);
  });
</script>

app/views/initial_evalutions/client_intake_evalution.html.erb
<ul class="menu-main">
  <li><a class="current" href="#" title="Form"><span>FORM</span></a></li>
  <li><a href="#" title="Mse"><span>Mse</span></a></li>
</ul>
<div class="box">
  <%= form_for @intake_evalution,:url => client_intake_initial_evalution_path(current_user.role,@client,@intake_evalution) do |f| %>
    <%= f.hidden_field :client_id,:value => @client.id %>
    <%= render :partial => "/initial_evalutions/form",:locals => {:f => f} %>
  <% end %>
</div>

app/views/initial_evalutions/edit.html.erb
<ul class="menu-main">
  <li><a class="current" href="#" title="Form"><span>FORM</span></a></li>
  <li><a href="#" title="Mse"><span>Mse</span></a></li>
</ul>
<div class="box">
  <%= form_for @intake_evalution,:url => initial_evalution_path(current_user.role,@intake_evalution),:method => :put do |f| %>
    <%= render :partial => "/initial_evalutions/form",:locals => {:f => f} %>
  <% end %>
</div>

app/views/initial_evalutions/new.html.erb
<ul class="menu-main">
  <li><a class="current" href="#" title="Form"><span>FORM</span></a></li>
  <li><a href="#" title="Mse"><span>Mse</span></a></li>
</ul>
<div class="box">
  <%= form_for @intake_evalution,:url => initial_evalutions_path(current_user.role,@intake_evalution) do |f| %>
    <%= f.hidden_field :case_id,:value => @case.id %>
    <%= f.hidden_field :client_id,:value => @client.id %>
    <%= render :partial => "/initial_evalutions/form",:locals => {:f => f} %>
  <% end %>
</div>