config/routes.rb
Rcms::Application.routes.draw do
  devise_for :users
  resources :settings,:path => ":role/settings/" do
    member do
      get :change_password
      put :update_password
    end
  end
  
  resources :notes
  namespace :client do
    resources :intakes
    resources :dashboards
    resources :individuals do
      member do
        get :medical
        post :medical_information
        get :personal
        post :personal_information
        get :minor
        post :minor_information
      end
    end
    resources :partners,:only => [:new,:create] do
      collection do
        get :partners_family
        post :partners_family_create
      end
    end
    resources :minors do
      member do
        get :medical
        post :medical_information
        get :personal
        post :personal_information
      end
    end
    resources :financials
    resources :career_assessments,:only => [:new,:create]
    resources :reduced_fees,:only => [:new,:create]
    resources :renewal_groups
  end
  
  namespace :counselor do
    resources :dashboards do
      collection do
        get :appointments
        get :case_list
        get :client_list
        get :counselor_status
        get :counselor_down_status
      end
    end
    resources :progress_notes do
      collection do
        post :appointment_progress
      end
    end
    resources :invoices do
      member do
        get :update_values
      end
    end
  end

  namespace :intake_coordinator do
    resources :dashboards do
      member do
        get :intake_details
        get :details
      end
      collection do
        post :assign_case_counselor
        get :calendar
        post :counselor_rooms
      end
    end
    resources :cases do
      collection do 
        get :search_cases
        get :case_list
        post :assign_case
      end
    end
  end
  
  namespace :admin do
    resources :case_prefixes
    resources :users do
      collection do
        get :clients
        get :search_clients
      end
      member do
        put :change_status
      end
    end
    resources :cpt_codes
    resources :misc_payments
    resources :dashboards
    resources :rooms do
      member do
        put :change_status
      end
    end
    resources :forms
    resources :payers do
      collection do
        get :search_payers
      end
    end
  end
  
  namespace :clinical_supervisor do
    resources :dashboards
  end
  
  namespace :clinical_director do
    resources :dashboards
  end
  
  namespace :admin_director do
    resources :dashboards
  end
  
  namespace :accounting_manager do
    resources :dashboards
  end
  
  namespace :reports_manager do
    resources :dashboards
  end
  
  namespace :scheduling_manager do
    resources :dashboards
  end
  
  resources :client_managements,:path => "/:role/client_managements" do
    member do
      post :upload_document
      get :add_client
    end
    collection do
      get :search
      get :search_form
    end
  end
  resources :case_managements,:path => "/:role/case_managements" do
    member do
      post :upload_document
      delete :remove_counselor
    end
    collection do
      post :add_counselor
      post :counselor_permisson
    end
  end
  resources :reminders,:path => "/:role/reminders"
  resources :documents,:path => "/:role/documents" do
    collection do
      get :case_documents
      post :upload_client_document
    end
  end
  
  resources :adolesment_intakes,:path => "/:role/adolesment_intakes" do
    member do
      get :client_adolesment_intake
      post :client_adolesment
    end
  end
  resources :discharge_summary,:path => "/:role/discharge_summary" do
    member do
      get :client_discharge_summary
      post :client_discharge
    end
  end
  resources :initial_evalutions,:path => "/:role/initial_evalutions" do
    member do
      get :client_intake_evalution
      post :client_intake
    end
  end
  resources :accountings,:path => "/:role/accountings" do
    collection do
      post :m_payment
      post :payer_account
      post :session_fee
    end
    member do
      get :update_session_payment
    end
  end
  
  resources :appointments,:path => "/:role/:shedule_id/appointments"
  resources :schedulings,:path => "/:role/schedulings"
  
  match "/:role/initial_evalutions/:case_id/new" => "initial_evalutions#new",:as => "initial_evalution_new"
  match "/:role/discharge_summary/:case_id/new" => "discharge_summary#new",:as => "discharge_summary_new"
  match "/:role/adolesment_intakes/:case_id/new" => "adolesment_intakes#new",:as => "adolesments_intake_new"
  match "/:role/intakes/:id" => "client/intakes#show",:as => "intake_form_details"
  match "/:role/reduced_fees/:id" => "client/reduced_fees#show",:as => "reduced_fee_details"

  root :to => 'home#index'

end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :document,:case_id,:intake_form_id,:user_id,:reduced_fee_id,:client_id,:case_num,:progress_note_id,:description,:adolesment_intake_id,:discharge_summary_id,:intake_evalution_id,:doc_type,:appointment_id
  attr_accessor :case_num,:appointment_id
  belongs_to :case
  belongs_to :client
  belongs_to :progress_note
  belongs_to :adolesment_intake
  belongs_to :discharge_summary
  belongs_to :intake_evalution
  belongs_to :intake_form
  belongs_to :reduced_fee
  belongs_to :user
  has_attached_file :document
  validates_attachment :document, :presence => true,
    :content_type => { :content_type => ["image/jpg","image/jpeg","application/pdf", "application/x-pdf"],:message => 'only jpg or pdf files' }
  validate :case_num_val
  
  def case_num_val
    cs = Case.find_by_number(self.case_num)
    if self.case_num and cs == nil
      self.errors.add(:case_num,"number not exists!")
    end
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_filter :is_intake_coordinator_or_counselor
  def index
    @client = Client.find(params[:client_id])
    @appointment = Appointment.find(session[:ap_id]) if session[:ap_id]
    @documents = @client.documents.order("created_at desc")
    @document = Document.new
  end
  
  def case_documents
    @case = Case.find(params[:case_id])
    @appointment = Appointment.find(session[:ap_id]) if session[:ap_id]
    @documents = @case.documents.order("created_at desc")
    @document = Document.new
  end
  
  def create
    @case = Case.find(params[:case_id])
    @appointment = Appointment.find(session[:ap_id]) if session[:ap_id]
    if params[:client_document][:document].blank?
      @blank = true
    else
      @doc = params[:client_document][:document]
      @blank = false
    end
  end
  
  def upload_client_document
    @appointment = Appointment.find(session[:ap_id]) if session[:ap_id]
    @client = Client.find(params[:client_id])
    if params[:client_document][:document].blank? and params[:client_document][:case_num].blank?
      @blank = true
      @doc_error = "can't be blank"
      @cas_error = "can't be blank"
    elsif params[:client_document][:document].blank?
      @blank = true
      @doc_error = "can't be blank"
    elsif params[:client_document][:case_num].blank?
      @blank = true
      @cas_error = "can't be blank"
    elsif !params[:client_document][:case_num].blank?
      @case = Case.find_by_number(params[:client_document][:case_num])
      puts "kapil"
      unless @case
        puts "ashok"
        @blank = true
        @cas_error = "case not found!"
      end
    else
      @doc = params[:client_document][:document]
      @blank = false
    end
  end
  
  def show
    @document = Document.find(params[:id])
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
  
  def document_type(role,cs,doc)
    "/"+role+"/"+doc+"/"+cs+"/new"
  end
  
  def document_redirect(role,cs,doc)
    if doc == "intake_evalution"
      "/"+role+"/initial_evalutions/"+cs+"/client_intake_evalution"
    elsif doc == "discharge_summary"
      "/"+role+"/discharge_summary/"+cs+"/client_discharge_summary"
    else doc == "adolesment_intake"
      "/"+role+"/adolesment_intakes/"+cs+"/client_adolesment_intake"
    end
  end
end

app/views/documents/_docments.html.erb
<table class="table-borLess" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tr>
    <td colspan="5">
      <ul class="list-breadCurm">
        <li class="active"><a href="#" title="Case Number">Lock</a></li>
        <li>Delete</li>
      </ul>
    </td>
  </tr>
  <% @documents.each do |document| %>
    <tr>
      <td>
        <% if document.doc_type == "progress_note" %>
          <%= link_to document.doc_type.split("_").join(" ").upcase, edit_counselor_progress_note_path(document.progress_note_id),:remote => true %>
        <% elsif document.doc_type == "intake_evalution" %>
          <%= link_to document.doc_type.split("_").join(" ").upcase,edit_initial_evalution_path(current_user.role,document.intake_evalution_id) %>
        <% elsif document.doc_type == "discharge_summary" %>
          <%= link_to document.doc_type.split("_").join(" ").upcase,edit_discharge_summary_path(current_user.role,document.discharge_summary_id) %>
        <% elsif document.doc_type == "adolesment_intake" %>
          <%= link_to document.doc_type.split("_").join(" ").upcase,edit_adolesment_intake_path(current_user.role,document.adolesment_intake_id) %>
        <% elsif document.doc_type == "intake_form"   %>
          <%= link_to ["individual","dating","family","marriage"].include?(document.intake_form.intake_type) ? "adult intake".upcase : document.intake_form.intake_type.split("_").join(" ").upcase,intake_form_details_path(:role => current_user.role,:id => document.intake_form_id) %>
        <% elsif document.doc_type == "reduced_fee" %>
          <%= link_to "reduced fee".upcase, reduced_fee_details_path(current_user.role,document.reduced_fee_id) %>
        <% elsif document.doc_type == "client_change" or document.doc_type == "staff_change" %>
          <%= link_to document.doc_type.split("_").join(" ").upcase,document_path(current_user.role,document) %>
        <% else %>
          <%= link_to document.document_content_type.upcase,document_path(current_user.role,document) %>
        <% end %>
      </td>
      <td><%= document.case ? document.case.number : '' %></td>
      <td>edited: <%= document.updated_at.strftime("%B %d, %Y").upcase %></td>
      <td>created: <%= document.created_at.strftime("%B %d, %Y").upcase %></td>
    </tr>
  <% end %>
</table>

app/views/documents/_form.html.erb
<%= render :partial => "/documents/docments" %>
<ul class="list-upload">
  <%= form_for @document,:url => upload_document_case_management_path(:id => @case.id,:document => @document) do |f| %>
    <%= f.hidden_field :case_id,:value => @case.id %>
    <%= f.hidden_field :appointment_id,:value => @appointment.id if @appointment %>
    <li>
      <div class="greenBox">Upload<br />a file</div>
      <div class="darkBoxGray">
        <h6 class="selectHeading"><span>1</span> Select a File</h6>
        <%= f.file_field :document,:class => "input-selectFile" %>
        <%= validation_error(@document.errors["document"]) %>
      </div>
      <div class="darkBoxGray lightBoxGray">
        <h6 class="selectHeading"></h6>
        <p></p>
        <div class="btn-createnew" style="margin-top:24px;"><input type="submit" value="Upload" title="Upload" name="" onclick="javascript:if ($('#document_case_num').val() === '') {
              alert('assign case');
              return false;
            }"/> <em></em></div>	
      </div>
      <div class="clearFix"></div>
    </li>
  <% end %>
  <%= form_for :client_document,:url => documents_path(:case_id => @case.id),:remote => true do |f| %>
    <li id="client_document">
      <div class="greenBox">Add a<br />Document</div>
      <div class="darkBoxGray">
        <h6 class="selectHeading"><span>1</span> Select a File</h6>
        <p><%= f.select :document,options_for_select([["Select",""],["Initial Evaluation","initial_evalutions"],["Discharge Summary","discharge_summary"],["Adolesement Intake","adolesment_intakes"]]),{},:style => 'padding: 7px;' %></p>
        <em id="doc_error" style="color:red;"></em>
      </div>
      <div class="darkBoxGray lightBoxGray">
        <h6 class="selectHeading"></h6>
        <p></p>
        <div class="btn-createnew" style="margin-top:24px;"><input type="submit" value="Create" title="Create" name="" /> <em></em></div>	
      </div>
      <div class="clearFix"></div>
    </li>
  <% end %>
</ul>

app/views/documents/_new.html.erb
<%= render :partial => "/documents/docments" %>
<ul class="list-upload">
  <%= form_for @document,:url => upload_document_client_management_path(:document => @document,:id => @client.id),:method => :post do |f| %>
    <%= f.hidden_field :appointment_id,:value => @appointment.id if @appointment %>  
    <li>
      <div class="greenBox">Upload<br />a file</div>
      <div class="darkBoxGray">
        <h6 class="selectHeading"><span>1</span> Select a File</h6>
        <%= f.file_field :document,:class => "input-selectFile" %>
        <%= validation_error(@document.errors["document"]) %>
      </div>
      <div class="darkBoxGray lightBoxGray">
        <h6 class="selectHeading"><span>2</span> ASSIGN CASE NUMBER</h6>
        <p><%= f.text_field :case_num,:class => "input-selectFile",:placeholder=>"IND-789-JK23" %></p>
        <%= validation_error(@document.errors["case_num"]) %>
        <div class="btn-createnew"><input type="submit" value="Upload" title="Upload" name="" onclick="javascript:if ($('#document_case_num').val() === '') {
              alert('assign case');
              return false;
            }"/> <em></em></div>	
      </div>
      <div class="clearFix"></div>
    </li>
  <% end %>
  <%= form_for :client_document,:url => upload_client_document_documents_path(current_user.role,@client_document,:client_id => @client.id),:method => :post,:remote => true do |f| %>
    <li id="client_document">
      <div class="greenBox">Add a<br />Document</div>
      <div class="darkBoxGray">
        <h6 class="selectHeading"><span>1</span> Select a File</h6>
        <p><%= f.select :document,options_for_select([["Select",""],["Initial Evaluation","initial_evalutions"],["Discharge Summary","discharge_summary"],["Adolesement Intake","adolesment_intakes"]]),{},:style => 'padding: 7px;' %></p>
        <em id="doc_error" style="color:red;"></em>
      </div>
      <div class="darkBoxGray lightBoxGray">
        <h6 class="selectHeading"><span>2</span> ASSIGN CASE NUMBER</h6>
        <p><%= f.text_field :case_num,:class => "input-selectFile",:placeholder=>"IND-789-JK23" %></p>
        <em id="cas_error"></em>
        <div class="btn-createnew"><input type="submit" value="Create" title="Create" name="" /> <em></em></div>	
      </div>
    </li>
  <% end %>
</ul>

app/views/documents/case_documents.js.erb
$("#display_details").html('<%= escape_javascript render :partial => "/documents/form" %>');

app/views/documents/create.js.erb
<% if @blank and @blank == true %>
  $("em#doc_error").html("can't be blank");
<% else %>
  window.location.href = "<%= document_type(current_user.role,@case.id.to_s,@doc) %>"
<% end %>

app/views/documents/index.js.erb
$("#display_details").html('<%= escape_javascript render :partial => "/documents/new" %>');

app/views/documents/show.html.erb
<% if @document.doc_type == "client_change" or @document.doc_type == "staff_change" %>
  <%= @document.description %>
<% else %>
  <% if Rails.env == 'development' %>
    <% if @document.document_content_type and @document.document_content_type.split("/")[0] == "image" %>
      <%= image_tag(@document.document) %>
    <% else %>
      <%= link_to "document","#{@document.document}",:target => "_blank" %>
    <% end %>
  <% end %>
<% end %>

app/views/documents/upload_client_document.js.erb
<% if @blank and @blank == true %>
  $("em#doc_error").html("<%= @doc_error %>");
  $("em#cas_error").html("<%= @cas_error %>");
<% else %>
  window.location.href = "<%= document_redirect(current_user.role,@client.id.to_s,@doc) %>"
<% end %>