config/routes.rb
Rcms::Application.routes.draw do
  devise_for :users
  resources :settings,:path => ":role/settings/" do
    member do
      get :change_password
      put :update_password
    end
  end
  
  resources :notes
  namespace :client do
    resources :intakes
    resources :dashboards
    resources :individuals do
      member do
        get :medical
        post :medical_information
        get :personal
        post :personal_information
        get :minor
        post :minor_information
      end
    end
    resources :partners,:only => [:new,:create] do
      collection do
        get :partners_family
        post :partners_family_create
      end
    end
    resources :minors do
      member do
        get :medical
        post :medical_information
        get :personal
        post :personal_information
      end
    end
    resources :financials
    resources :career_assessments,:only => [:new,:create]
    resources :reduced_fees,:only => [:new,:create]
    resources :renewal_groups
  end
  
  namespace :counselor do
    resources :dashboards do
      collection do
        get :appointments
        get :case_list
        get :client_list
        get :counselor_status
        get :counselor_down_status
      end
    end
    resources :progress_notes do
      collection do
        post :appointment_progress
      end
    end
    resources :invoices do
      member do
        get :update_values
      end
    end
  end

  namespace :intake_coordinator do
    resources :dashboards do
      member do
        get :intake_details
        get :details
      end
      collection do
        post :assign_case_counselor
        get :calendar
        post :counselor_rooms
      end
    end
    resources :cases do
      collection do 
        get :search_cases
        get :case_list
        post :assign_case
      end
    end
  end
  
  namespace :admin do
    resources :case_prefixes
    resources :users do
      collection do
        get :clients
        get :search_clients
      end
      member do
        put :change_status
      end
    end
    resources :cpt_codes
    resources :misc_payments
    resources :dashboards
    resources :rooms do
      member do
        put :change_status
      end
    end
    resources :forms
    resources :payers do
      collection do
        get :search_payers
      end
    end
  end
  
  namespace :clinical_supervisor do
    resources :dashboards
  end
  
  namespace :clinical_director do
    resources :dashboards
  end
  
  namespace :admin_director do
    resources :dashboards
  end
  
  namespace :accounting_manager do
    resources :dashboards
  end
  
  namespace :reports_manager do
    resources :dashboards
  end
  
  namespace :scheduling_manager do
    resources :dashboards
  end
  
  resources :client_managements,:path => "/:role/client_managements" do
    member do
      post :upload_document
      get :add_client
    end
    collection do
      get :search
      get :search_form
    end
  end
  resources :case_managements,:path => "/:role/case_managements" do
    member do
      post :upload_document
      delete :remove_counselor
    end
    collection do
      post :add_counselor
      post :counselor_permisson
    end
  end
  resources :reminders,:path => "/:role/reminders"
  resources :documents,:path => "/:role/documents" do
    collection do
      get :case_documents
      post :upload_client_document
    end
  end
  
  resources :adolesment_intakes,:path => "/:role/adolesment_intakes" do
    member do
      get :client_adolesment_intake
      post :client_adolesment
    end
  end
  resources :discharge_summary,:path => "/:role/discharge_summary" do
    member do
      get :client_discharge_summary
      post :client_discharge
    end
  end
  resources :initial_evalutions,:path => "/:role/initial_evalutions" do
    member do
      get :client_intake_evalution
      post :client_intake
    end
  end
  resources :accountings,:path => "/:role/accountings" do
    collection do
      post :m_payment
      post :payer_account
      post :session_fee
    end
    member do
      get :update_session_payment
    end
  end
  
  resources :appointments,:path => "/:role/:shedule_id/appointments"
  resources :schedulings,:path => "/:role/schedulings"
  
  match "/:role/initial_evalutions/:case_id/new" => "initial_evalutions#new",:as => "initial_evalution_new"
  match "/:role/discharge_summary/:case_id/new" => "discharge_summary#new",:as => "discharge_summary_new"
  match "/:role/adolesment_intakes/:case_id/new" => "adolesment_intakes#new",:as => "adolesments_intake_new"
  match "/:role/intakes/:id" => "client/intakes#show",:as => "intake_form_details"
  match "/:role/reduced_fees/:id" => "client/reduced_fees#show",:as => "reduced_fee_details"

  root :to => 'home#index'

end

app/controllers/accountings_controller.rb
class AccountingsController < ApplicationController
  
  def new
    @case = Case.find(params[:case_id]) if params[:case_id]
    @client = Client.find(params[:client_id]) if params[:client_id]
    @client_payments = @case.session_payments.where("client_id IS NOT NULL") if @case
    @payer_payments = @case.session_payments.where("payer_id IS NOT NULL") if @case
    @client_payments = @client.session_payments.where("client_id IS NOT NULL") if @client
    @payer_payments = @client.session_payments.where("payer_id IS NOT NULL") if @client
    @session = SessionPayment.new
    @m_payment = MiscellaneousPayment.new
    @payer_account = PayerAccount.new
    @session_fee = SessionFee.new
  end
  
  def create
    @case = Case.find(params[:session_payment][:case_id]) if params[:session_payment][:case_id]
    @client = Client.find(params[:client_id]) if params[:client_id]
    @session = SessionPayment.new(params[:session_payment])
    @session.client_id = @session.payment_name.split(",").last if @session.payment_name and @session.payment_name.split(",").first == "Client"
    @session.payer_id = @session.payment_name.split(",").last if @session.payment_name and @session.payment_name.split(",").first == "Payer"
    @session.save
    render
  end
  
  def update
    @case = Case.find(params[:session_payment][:case_id]) if params[:session_payment][:case_id]
    @client = Client.find(params[:client_id]) if params[:client_id]
    @session = SessionPayment.find(params[:id])
    @session.client_id = params[:session_payment][:payment_name].split(",").last if params[:session_payment][:payment_name] and params[:session_payment][:payment_name].split(",").first == "Client"
    @session.payer_id = params[:session_payment][:payment_name].split(",").last if params[:session_payment][:payment_name] and params[:session_payment][:payment_name].split(",").first == "Payer"
    unless @session.session_status == "completed"
      @session.balance = @session.fee - params[:amount].to_i if @session.fee
    end
    @session.update_attributes(params[:session_payment])
  end
  
  def m_payment
    @m_payment = MiscellaneousPayment.new(params[:miscellaneous_payment])
    @client = Client.find(@m_payment.client_id) if !@m_payment.client_id.blank?
    @case = Case.find(@m_payment.case_id) if !@m_payment.case_id.blank?
    if @m_payment.save
    else
    end
    render
  end
  
  def payer_account
    @payer_account = PayerAccount.new(params[:payer_account])
    @payer_account.save
    render
  end
  
  def session_fee
    @session_fee = SessionFee.new(params[:session_fee])
    @session_fee.save
  end
  
  def update_session_payment
    @session = SessionPayment.find(params[:id])
    @case = Case.find(@session.case_id)
  end
end

app/helpers/accountings_helper.rb
module AccountingsHelper
end

app/views/accountings/_case_sessions.html.erb
<div id="session_form">
  <%= render :partial => "accountings/session_form" %>
</div>
<div id="misc_form">
  <%= render :partial => "accountings/misce_form" %>
</div>
<%= render :partial => "accountings/client_accounts" %>
<div class="clearFix"></div>
<div class="payer">Payer 2 Sheet</div>		
<div class="grayBox darkGrayBox">
  <div id="payer_form">
    <%= render :partial => "accountings/payer_form" %>
  </div>
  <div id="session_fee_form">
    <%= render :partial => "accountings/session_fee_form" %>
  </div>
</div>

<%= render :partial => "accountings/payer_accounts" %>
<style>
  select{
    padding: 4px 3px;
  }
  .btn-createnew{
    bottom: -3px;
  }
</style>

app/views/accountings/_client_accounts.html.erb
<table class="table-accounting" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tr>
    <td>Payment Date</td>
    <td>Case Number</td>
    <td>SESSION <br />STATUS</td>
    <td>AUTH</td>
    <td>FEE</td>
    <td>COPAY</td>
    <td>Amount</td>
    <td>DEBIT</td>
    <td>BALANCE</td>
  </tr>
  <% @client_payments.each do |session_payment| %>
    <tr onclick="UpdateSessionPayment(<%= "'#{current_user.role}'" %>, <%= "'#{session_payment.id}'" %>)">
      <td><span><%= session_payment.session_date %></span></td>
      <td>SESSION <span><%= session_payment.case ? session_payment.case.number : '' %></span></td>
      <td><%= session_payment.session_status %></td>
      <td><%= session_payment.auth %></td>
      <% ses_fee = SessionFee.where("case_id = '#{session_payment.case_id}' and start_date < '#{session_payment.session_date}'").last %>
      <td><%= ses_fee ? ses_fee.fee : session_payment.fee%></td>
      <td><%= session_payment.copay %></td>
      <td><%= session_payment.amount %></td>
      <td><%= session_payment.debit %></td>
      <td class="column-green"><%= session_payment.balance %></td>
    </tr>
  <% end %>
</table>

<script type="text/javascript">
  function UpdateSessionPayment(role, ss) {
    $.ajax({
      url: "/" + role + "/accountings/" + ss + "/update_session_payment/",
      type: "GET",
      dataType: "script",
      success: function(data) {
      }
    });
  }
</script>

app/views/accountings/_misce_form.html.erb
<% if @client %>
  <%= form_for @m_payment,:url => m_payment_accountings_path(current_user.role,@m_payment),:method => :post,:remote => true do |f| %>
    <%= f.hidden_field :case_id,:value => @case.id if @case %> 
    <%= f.hidden_field :client_id,:value => @client.id if @client %> 
    <div class="grayBox lightGrayBox">
      <%= f.error_messages %>
      <div class="sessionPayment">
        <div class="commentPlus" style="cursor: pointer;" onclick="javascript:$('#comment1').toggle('slow')">COMMENT</div>
        <h6 class="GrayBoxHeading">MISCELLANEOUS PAYMENT</h6>
      </div>
      <div class="payment">
        <div>
          <p>Date</p>
          <%= f.date_select :pay_date, {:include_blank => true, :default => nil,:start_year => 1930} %>
        </div>
        <div>
          <p>Description</p>
          <%= f.text_field :description,:class => "input-namePayment input-datePayment" %>
        </div>
        <div>
          <p>Item</p>
          <%= f.text_field :item,:class => "input-namePayment input-datePayment" %>
        </div>
        <div>
          <p>Payment Type</p>
          <%= f.select :payment_type,%W(cash ckeque credit_card) %>
        </div>
      </div>
      <div id="comment1" style="display: none;">
        <p>Comment</p>
        <%= f.text_area :comment,:rows => 2,:cols => 20,:class => "textarea-comment" %>
      </div>
      <div class="btn-createnew">
        <input type="submit" title="SAVE" value="SAVE" name="" /><em></em>
      </div>
    </div>
  <% end %>
<% end %>

app/views/accountings/_payer_accounts.html.erb
<table class="table-accounting" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tr>
    <td>Payment Date</td>
    <td>Case Number</td>
    <td>SESSION <br />STATUS</td>
    <td>AUTH</td>
    <td>FEE</td>
    <td>COPAY</td>
    <td>Amount</td>
    <td>DEBIT</td>
    <td>BALANCE</td>
  </tr>
  <% @payer_payments.each do |session_payment| %>
    <tr>
      <td><span><%= session_payment.session_date %></span></td>
      <td>SESSION <span><%= session_payment.case ? session_payment.case.number : '' %></span></td>
      <td><%= session_payment.session_status %></td>
      <td><%= session_payment.auth %></td>
      <% ses_fee = SessionFee.where("case_id = '#{session_payment.case_id}' and start_date < '#{session_payment.session_date}'").last %>
      <td><%= ses_fee ? ses_fee.fee : session_payment.fee%></td>
      <td><%= session_payment.copay %></td>
      <td><%= session_payment.amount %></td>
      <td><%= session_payment.debit %></td>
      <td class="column-green"><%= session_payment.balance %></td>
    </tr>
  <% end %>
</table>

app/views/accountings/_payer_form.html.erb
<%= form_for @payer_account,:url => payer_account_accountings_path(current_user.role,@payer_account),:remote => true do |f| %>
  <%= f.error_messages %>
  <div class="sessionPayment">
    <h6 class="GrayBoxHeading">ACCOUNT INFORMATION
      <%= f.select :case_id,options_for_select([["Select",""]]+Case.all.map{|a| [a.number,a.id]},:selected => f.object.case_id) %>
    </h6>
  </div>
  <div class="info payment">
    <div>
      <p>Start Date</p>
      <%= f.date_select :start_date, {:include_blank => true, :default => nil,:start_year => 1930} %>
    </div>
    <div>
      <p>Payer 2</p>
      <%= f.select :payer_id,options_for_select([["Select",""]]+Payer.all.map{|a| [a.name_of_org,a.id]},:selected => f.object.payer_id) %>
    </div>
    <div>
      <p>Client Id</p>
      <%= f.text_field :client_id,:class=>"input-info input-Authoriz",:title=>"client id" %>
    </div>
    <div>
      <p>Authorizations</p>
      <%= f.text_field :auth,:class=>"input-info input-Authoriz",:title=>"Authorizations", :placeholder=>"5"  %>
    </div>
    <div>
      <p>Amt Per Session</p>
      <%= f.text_field :amount,:class=>"input-info input-Authoriz",:title=>"Authorizations", :placeholder=>"$85"  %>
    </div>
  </div>
  <div class="btn-createnew">
    <input type="submit" title="Save" value="Save" name="" /><em></em>
  </div>
<% end %>

app/views/accountings/_session_fee_form.html.erb
<%= form_for @session_fee,:url => session_fee_accountings_path(current_user.role,@session_fee),:remote => true do |f| %>
  <%= f.error_messages %>
  <div class="sessionPayment">
    <h6 class="GrayBoxHeading">ACCOUNT INFORMATION
      <%= f.select :case_id,options_for_select([["Select",""]]+Case.all.map{|a| [a.number,a.id]},:selected => f.object.case_id) %>
    </h6>
  </div>
  <div class="info payment">
    <div>
      <p>Fee</p>
      <%= f.text_field :fee,:class=>"input-info input-Authoriz",:title=>"Fee"  %>
    </div>
    <div>
      <p>Start Date</p>
      <%= f.date_select :start_date, {:include_blank => true, :default => nil,:start_year => 1930} %>
    </div>
  </div>
  <div class="btn-createnew">
    <input type="submit" title="Save" value="Save" name="" /><em></em>
  </div>
<% end %>

app/views/accountings/_session_form.html.erb
<%= form_for @session,:url => @session.new_record? ? accountings_path(current_user.role,@session) : accounting_path(current_user.role,@session), :method => @session.new_record? ? :post : :put,:remote => true do |f| %>
  <%= f.hidden_field :action_name,:value => "accounting" %> 
  <%= hidden_field_tag "client_id",@client.id if @client %>
  <%= f.hidden_field :case_id,:value => @case.id if @case %>
  <div class="grayBox">
    <%= f.error_messages %>
    <div class="sessionPayment">
      <div class="commentPlus" style="cursor: pointer;" onclick="javascript:$('#comment').toggle('slow')">COMMENT</div>
      <h6 class="GrayBoxHeading">SESSION PAYMENT</h6>
    </div>
    <div class="payment">
      <div>
        <p>Date</p>
        <%= f.date_select :session_date, {:include_blank => true, :default => nil,:start_year => 1930} %>
      </div>
      <div>
        <p>Case Number</p>
        <% if @case %>
          <%= @case.number %>
        <% elsif @client %>
          <%= f.select :case_id,options_for_select([["Select",""]]+Case.all.map{|a| [a.number,a.id]},:selected => f.object.case_id) %>
        <% end %>
      </div>
      <div>
        <p>Amount</p>
        <%= f.text_field :amount,:class => "input-amountPayment input-datePayment" %>
      </div>
      <div>
        <p>Payment Type</p>
        <%= f.select :payment_type,%W(cash ckeque credit_card) %>
      </div>
      <div>
        <p>Payer</p>
        <% if @case %>
          <%= f.select :payment_name,options_for_select([["Select",""]]+@case.case_clients.all.map{|a| [a.client.full_name,"Client,#{a.client_id}"]}+Payer.all.map{|a| [a.name_of_org,"Payer,#{a.id}"]},:selected => f.object.payment_name) %>
        <% elsif @client %>
          <%= f.select :payment_name,options_for_select([["Select",""],[@client.full_name,"Client,#{@client.id}"]]+Payer.all.map{|a| [a.name_of_org,"Payer,#{a.id}"]},:selected => f.object.payment_name) %>
        <% end %>
      </div>
      <!--<div>
        <p>Amount</p>
  <%#=  f.text_field :payment_amount,:class => "input-datePayment" %>
      </div>-->
    </div>
    <div id="comment" style="display: none;">
      <p>Comment</p>
      <%= f.text_area :comment,:rows => 2,:cols => 20,:class => "textarea-comment" %>
    </div>
    <div class="btn-createnew">
      <input type="submit" title="SAVE" value="SAVE" name="" /><em></em>
    </div>
  </div>
<% end %>

app/views/accountings/create.js.erb
<% if @session.errors.any? %>
  $("#session_form").html('<%= escape_javascript render :partial => "/accountings/session_form" %>');
<% else %>
  window.location.reload();
<% end %>

app/views/accountings/m_payment.js.erb
<% if @m_payment.errors.any? %>
  $("#misc_form").html('<%= escape_javascript render :partial => "/accountings/misce_form" %>');
<% else %>
  window.location.reload();
<% end %>

app/views/accountings/new.js.erb
  $("#display_details").html('<%= escape_javascript render :partial => "/accountings/case_sessions" %>');

app/views/accountings/payer_account.js.erb
<% if @payer_account.errors.any? %>
  $("#payer_form").html('<%= escape_javascript render :partial => "/accountings/payer_form" %>');
<% else %>
  window.location.reload();
<% end %>

app/views/accountings/session_fee.js.erb
<% if @session_fee.errors.any? %>
  $("#session_fee_form").html('<%= escape_javascript render :partial => "/accountings/session_fee_form" %>');
<% else %>
  window.location.reload();
<% end %>

app/views/accountings/update.js.erb
<% if @session.errors.any? %>
  $("#session_form").html('<%= escape_javascript render :partial => "/accountings/session_form" %>');
<% else %>
  window.location.reload();
<% end %>

app/views/accountings/update_session_payment.js.erb
  $("#session_form").html('<%= escape_javascript render :partial => "/accountings/session_form" %>');